# Generated by Django 4.2.5 on 2023-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
